# Generated by Django 4.0.4 on 2022-06-06 11:10

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalquiz',
            name='creator',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ManyToManyField(to='main.categoties', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='count',
            field=models.IntegerField(verbose_name='Количество опросов'),
        ),
        migrations.AlterField(
            model_name='categoties',
            name='reviews',
            field=models.IntegerField(validators=[main.models.validate_even], verbose_name='Оценка категории'),
        ),
        migrations.AlterField(
            model_name='historicalauthors',
            name='count',
            field=models.IntegerField(verbose_name='Количество опросов'),
        ),
        migrations.AlterField(
            model_name='historicalcategoties',
            name='reviews',
            field=models.IntegerField(validators=[main.models.validate_even], verbose_name='Оценка категории'),
        ),
        migrations.AlterField(
            model_name='historicalquiz',
            name='description',
            field=models.TextField(verbose_name='Описание опроса'),
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='creator',
        ),
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ManyToManyField(to='main.authors', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(verbose_name='Описание опроса'),
        ),
    ]
